CREATE DATABASE BankManagmentSystem

CREATE TABLE BANK_INFO
(
BANK_NAME varchar(20),
BANK_CODE int,
BANK_ADDRESS varchar(50),
PRIMARY KEY (BANK_CODE)
);
INSERT INTO BANK_INFO
VALUES('HBL','101','HAQNAWAZ PARK');

CREATE TABLE CUSTOMER_PERSONAL_INFO
(
CUSTOMER_NAME varchar(20),
CUSTOMER_ID int,
GUARDIAN_NAME varchar(20),
DATE_OF_BIRTH date,
ADDRESS varchar(50),
GENDER varchar(1),
MARTIAL_STATUS varchar(20),
CITIZENSHIP varchar(20),
PRIMARY KEY (CUSTOMER_ID),
);

INSERT INTO CUSTOMER_PERSONAL_INFO
VALUES ('Muhammad Talha','15403','Muhammad Irfan','02-05-1996','indus kalooni near river','M','Married','Pakistani');

CREATE TABLE CUSTONER_REFERENCE_INFO
(
CUSTOMER_ID int,
REFERENCE_ACC_NAME varchar(20),
REFERENCE_ACC_NO int,
REFERENCE_ADDRESS varchar(50),
RELATION varchar(20),
CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY (CUSTOMER_ID),
);

DROP TABLE CUSTONER_REFERENCE_INFO

CREATE TABLE CUSTOMER_REFERENCE_INFO
(
CUSTOMER_ID int,
REFERENCE_ACC_NAME varchar(20),
REFERENCE_ACC_NO int,
REFERENCE_ADDRESS varchar(50),
RELATION varchar(20),
);
INSERT INTO CUSTOMER_REFERENCE_INFO
VALUES ('12140','ASIM KHAN','567011','TANK ADDA','FRIEND');

CREATE TABLE ACCOUNT_INFO
(
ACCOUNT_NO int,
CUSTOMER_ID int,
ACCOUNT_TYPE varchar(20),
REGISTRATION_DATE date,
ACTIVATION_DATE date,
BANK_CODE int,
INITIAL_DEPOSIT int,
CONSTRAINT ACC_INFO_PK PRIMARY KEY (ACCOUNT_NO),
CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO (CUSTOMER_ID),
CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(BANK_CODE) REFERENCES BANK_INFO (BANK_CODE),
);

INSERT INTO ACCOUNT_INFO
VALUES('123099','15403','CURRENT ACCOUNT','2016-09-11','2016-11-23','101','50000');

